name: Angular CI Workflow

on: [push, pull_request]

env:
  DOCKER_IMAGE_NAME: 'network-impairment-gateway-ui'
  SONAR_ORGANIZATION: 'dewcservices'
  SONAR_PROJECT_KEY: 'dewcservices_network-impairment-gateway-ui'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Custom Angular.js action
        uses: ./.github/actions/node
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          node_version: 'lts/*'
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_args: >
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
          docker_image_name: ${{ env.DOCKER_IMAGE_NAME }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
